### ISSUE TITLE
Mobile First

### ISSUE THREAD

**Issue by singerxt** [grzegorzSpiewak/Single-Page-Music-Portfolio#3]
### Opis

Czasami nie potrzebnie używasz `max-width` w css'ach. Postaraj się zrefactorować swój kod tak aby ich nie używał a zamiast max-width używaj min-width.
### Technologia

Patern mobile first

``` scss
.selector {
  color: red; // mobile

  @media (min-width: 640px) {
     color: yellow; // tablet
  }

  @media (min-width: 1024px) {
     color: green; // desktop
  }
}
```
